[package]
name = "ostring_base"
version = "1.0.0"
edition = "2021"
authors = ["weak_cat"]
description = "ostring base crate include some basic function"
license = "MIT"
repository = "https://github.com/Weakcat/ostring_base.git"

[dependencies]
anyhow = "1.0.93"
tokio = { version = "1.41.1", features = ["full"] }
sysinfo = "0.32.0"
auto-launch = "0.5"
once_cell = "1.20.2"
serialport = "4.6.0"
serde = { version = "1.0.215", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.41.1", features = ["full"] }
serialport = "4.6.0"